# Generated by Django 5.1.5 on 2025-03-28 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='orderid',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
