# Generated by Django 5.1.5 on 2025-04-07 06:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_cart_orderid'),
    ]

    operations = [
        migrations.CreateModel(
            name='orderdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('totalamount', models.FloatField()),
                ('phone', models.BigIntegerField()),
                ('address', models.TextField()),
                ('paymode', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=True)),
                ('razorpay_order_id', models.CharField(blank=True, max_length=255, null=True)),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.product')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.registr')),
            ],
        ),
        migrations.AlterField(
            model_name='payment',
            name='order_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.orderdata'),
        ),
        migrations.DeleteModel(
            name='order',
        ),
    ]
