# Generated by Django 5.1.5 on 2025-04-07 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_orderdata_alter_payment_order_id_delete_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdata',
            name='product_id',
        ),
    ]
