# Generated by Django 5.2 on 2025-04-27 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_rename_name_contact_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='contact',
            new_name='contactpage',
        ),
    ]
